### ISSUE TITLE
TDF applied to consummer groups instead of prey

### ISSUE THREAD

**Issue by CWR-05** [brianstock/MixSIAR#293] opened 2021-10-14 22:20 UTC
Hello,

I have 2 species with juveniles and adults in each species. I do not wish to run the models separately. I was wondering how to build the discrimination csv file with the proper discrimination factor for each group of consumers (cause they are pretty different), I haven't found an example that applies TDF by consumer instead of by prey. Should I enter one average +/- SD TDF for the 4 groups, or is there a way to inform MixSIAR that the TDF should apply to consumer and not prey?

Best regards,
Chloé

**Comment by brianstock** [comment] 2021-10-27 14:41
Hi Chloe,

I believe this is a duplicate of https://github.com/brianstock/MixSIAR/issues/176. 

MixSIAR does not allow you to enter TDF by consumer factor/group, but the sources can differ by consumer group and you can manually adjust them by the group-specific TDFs. Note that you'll have to add the source and TDF variances, then take the square root to enter the appropriate SD. This also means you'd have to use the mean/sd/n option for sources, can't fit the raw source data. Implications of this are described in supplement 1 of the MixSIAR description [paper](https://peerj.com/articles/5096/).

Good luck,
Brian

**Closed as completed by brianstock** 2021-10-27 14:41 UTC
